### ISSUE TITLE
Sunsetting

### ISSUE THREAD

**Issue by lelong37** [miroslavpopovic/urf#1]
@miroslavpopovic, we are currently consolidating URF and are completed with migration from CodePlex. In this process we've reached out to several URF repository and NuGet owners requesting to sunset, dlist and deactivate their URF repositories and/or packages, to help with the ambiguity of since source for URF and at the same time we would love, welcome and encourage any PR's (Pull Request) on any of the official URF repositories. Please let us know if there's anything else needed or we can help with and if it's OK for you to delist and deactivate this repo to help us with this consolidation effort, thanks..

URF Organization:
https://github.com/urfnet

**Comment by miroslavpopovic** [comment]
Thanks for letting me know. I'll delete this repository.
